### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by alehuo** [Walther/tinybrain#4]
Projekti ladattu 5.12. klo 19:57.

Käyttöohjeet ovat selkeät; sain projektin asennettua helposti ja suoritettua yarn test -komennon.

Testejä on luotu todella kattavasti ja ne kaikki menevät läpi, mutta toivoisin esim. Codecov-palvelun käyttöä, jotta rivikattavuudesta saisi lisätietoa.

Koodi on siistiä ja hyvin dokumentoitua, jonka lisäksi omia tietorakenteita on käytetty. Hyvä! Taulukot on suljettu Object.seal -metodilla, jotta niille saadaan kiinteä koko.

docs-kansiossa on laadittu dokumentaatiota sovelluksen eri komponenteista kattavasti. Voisit lisäksi luoda koko koodin kattavan dokumentaation käyttämällä JsDOC-kirjastoa.

Projektisi näyttää melko valmiilta, joten mietin, että seuraavana voisit lähteä testaamaan näytönohjaimen hyödyntämistä matriisilaskutoimituksissa käyttäen GPU.js -kirjastoa.

**Comment by Walther** [comment]
Kiitokset palautteesta!

- Kiitos vinkistä. Kokeilin codecov, mutta vaihdoin coveralls:iin, jota olen käyttänyt aiemmin. Nyt löytyy kattavuustieto
- jsDoc lisätty `docs/jsdoc/` kansioon
- GPU.js on ollut harkinnassa, katsotaan ehdinkö...
